# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 24a54589bf80c33b415482fa647ca82c42d60ed5147dd922ef42fd2f0b5299450e4ba2a70fc3e15fd5313f32e3937227d32bffff82717c7ae967bfb5bae03076

test:
  secret_key_base: cc4e5021d55158220fa70c4295128742f797d5e090d63f262dbd01bdff409da140e2f772f4fed8ce4a22e2e10aa68c9578a420b26757afb68a467e3789a1eb4e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
